# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zero Document Format
email: zdf@zerodarktech.com
description: > # this means to ignore newlines until "baseurl:"
  The web is accelerating at a rapid pace. Why are our documents still in the stoneage?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zerodarktech.com" # the base hostname & protocol for your site
github_username:  Team-ZDF

# Build settings
markdown: kramdown
